
const traitLabels={ancient:'ancient history',art:'art',churches:'architecture & churches',scenery:'scenery',beach:'beach / pool time',food:'food',wine:'wine & drinks',shopping:'shopping',nightlife:'nightlife',smalltown:'small towns',famous:'famous sights',local:'local life',outdoor:'outdoors',photo:'photography',relax:'relaxation',maker:'hands-on experiences',gardens:'gardens',romance:'special / romantic experiences'};
function naturalList(a){if(!a.length)return'';if(a.length===1)return a[0];if(a.length===2)return a[0]+' and '+a[1];return a.slice(0,-1).join(', ')+', and '+a.at(-1)}
function show(id,label='',pct=0){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');const p=['modeScreen','interestScreen','priorityScreen','avoidScreen'].includes(id);document.getElementById('progressWrap').classList.toggle('hidden',!p);document.getElementById('startOverHeader').classList.toggle('hidden',id==='welcomeScreen');if(p){document.getElementById('progressLabel').textContent=label;document.getElementById('progressBar').style.width=pct+'%'}updateHeader();scrollTo({top:0,behavior:'smooth'})}
function totalSaved(){let n=0;state.savedExp.forEach(s=>n+=s.size);return n}
function updateHeader(){const n=state.savedRegions.size+totalSaved();document.getElementById('tripIdeasHeaderCount').textContent=n;document.getElementById('tripIdeasHeader').classList.toggle('hidden',!n)}
function enable(btn,on,text){btn.disabled=!on;btn.textContent=text;btn.className=on?'px-6 py-3 rounded-xl bg-basil text-white font-bold':'px-6 py-3 rounded-xl bg-stone-200 text-stone-400 font-bold cursor-not-allowed'}
function resetAll(){Object.assign(state,{mode:null,selected:new Set(),anchors:new Set(),avoids:new Set(),savedRegions:new Set(),savedExp:new Map(),regionPrefs:new Map(),reach:new Map(),explored:new Set(),regionMonth:new Map(),currentRegion:null,tripTab:'region',tripLength:null,exactDays:null,layouts:new Map(),compare:null});show('welcomeScreen')}
function weights(){const w={};if(state.mode==='know')state.selected.forEach(x=>w[x]=(w[x]||0)+1);else state.selected.forEach(id=>{const it=discoveryCatalog.find(x=>x.id===id);if(it)Object.entries(it.maps).forEach(([k,v])=>w[k]=(w[k]||0)+v)});state.anchors.forEach(id=>{if(state.mode==='know')w[id]=(w[id]||0)+2.4;else{const it=discoveryCatalog.find(x=>x.id===id);if(it)Object.entries(it.maps).forEach(([k,v])=>w[k]=(w[k]||0)+v*2.4)}});return w}
function anchorTraits(){const a=[];state.anchors.forEach(id=>{if(state.mode==='know')a.push(id);else{const it=discoveryCatalog.find(x=>x.id===id);if(it)Object.entries(it.maps).sort((x,y)=>y[1]-x[1]).slice(0,2).forEach(([k])=>a.push(k))}});return[...new Set(a)]}
function regionScore(r){const w=weights();let raw=0,tw=0;Object.entries(w).forEach(([t,v])=>{raw+=(r.traits[t]||0)*v;tw+=v});let s=tw?raw/tw*8.1:40;s+=Math.max(0,7-r.obviousness)*.7;let pen=0;state.avoids.forEach(a=>{let l=r.frictions[a]||0;if(a==='heat'||a==='cold')l*=.28;pen+=l*.55});s-=Math.min(18,pen);anchorTraits().forEach(t=>{if((r.traits[t]||0)>=9)s+=3.2});return Math.max(15,Math.min(99,s))}
function fit(s){return s>=78?'Exceptional Fit':s>=66?'Strong Fit':s>=54?'Good Fit':'Possible Fit'}
function ranked(){return regions.map(r=>({...r,_score:regionScore(r)})).sort((a,b)=>b._score-a._score)}
function contributors(r,n=2){const w=weights();return Object.entries(w).map(([t,v])=>({t,val:(r.traits[t]||0)*v})).filter(x=>x.val>0).sort((a,b)=>b.val-a.val).slice(0,n)}
function whyRegion(r){const c=contributors(r,2);if(!c.length)return r.name;let s=`It is high on your list because of your interest in ${naturalList(c.map(x=>traitLabels[x.t]))}.`;const ex=c.map(x=>r.examples[x.t]).filter(Boolean);if(ex[0])s+=' '+ex[0]+'.';if(ex[1])s+=' '+ex[1]+'.';return s}
function regionTitle(r){if(r.id==='tuscany'){const w=weights(),culture=(w.art||0)+(w.churches||0)+(w.famous||0),country=(w.smalltown||0)+(w.scenery||0)+(w.wine||0)+(w.maker||0)+(w.local||0);if(country>culture*1.2)return'Tuscany, with Florence as a cultural anchor';if(culture>country*1.15)return'Florence, with Tuscany beyond the city'}return r.name}


function imageFor(id){return null}
function expPhoto(e){return e.region==='rome'?(romeExperiencePhotos[e.id]||romeRegionPhoto):null}
function reachMeta(e){return experienceReach[e.id]||{zone:'core',note:'Core area · part of the main city or base experience.'}}
function reachLevel(id){return state.reach.get(id)||'core'}
function reachAllows(e){return zoneRanks[reachMeta(e).zone]<=zoneRanks[reachLevel(e.region)]}
function reachBadge(e){const m=reachMeta(e);return`<span class="inline-flex mt-2 px-2.5 py-1 rounded-full text-xs font-bold ${m.zone==='core'?'bg-mist text-basil':m.zone==='nearby'?'bg-[#eef3f8] text-[#3f607b]':m.zone==='daytrip'?'bg-cream text-[#7b5a24]':'bg-[#fff0ed] text-tomato'}">${zoneLabels[m.zone]}</span>`}
function baseLabel(id){return baseLabels[id]||regionById[id]?.short||'your base'}
function regionResultHeader(r,i){
  return`<div class="p-5 pb-2"><div class="inline-flex bg-cream border border-warm px-3 py-1 rounded-full text-xs font-bold mb-4">#${i+1} · ${fit(r._score)}</div><h3 class="font-display text-3xl font-bold">${regionTitle(r)}</h3>${r.subtitle?`<p class="text-sm text-stone-500 mt-1">${r.subtitle}</p>`:''}</div>`
}
function renderInterests(){const cat=state.mode==='know'?interestCatalog:discoveryCatalog;interestEyebrow.textContent=state.mode==='know'?'What sounds good?':'No travel expertise required';interestTitle.textContent=state.mode==='know'?'What would make this feel like a great Italy trip?':'Which ordinary-day ideas sound enjoyable?';interestSubtitle.textContent=state.mode==='know'?'Choose everything that matters. You do not have to be only one kind of traveler.':'Choose anything that appeals. You do not need to know anything about Italy yet.';interestGrid.innerHTML='';cat.forEach(it=>{const b=document.createElement('button');b.className='pick text-left border-2 border-stone-200 rounded-xl p-4 bg-white'+(state.selected.has(it.id)?' selected':'');b.innerHTML=`<div class="flex gap-3"><div class="text-xl">${it.icon}</div><div><div class="font-bold">${it.label}</div><div class="text-sm text-stone-500 mt-1">${it.desc}</div></div></div>`;b.onclick=()=>{state.selected.has(it.id)?(state.selected.delete(it.id),state.anchors.delete(it.id)):state.selected.add(it.id);renderInterests()};interestGrid.appendChild(b)});interestCount.textContent=`${state.selected.size} selected`;enable(interestNext,state.selected.size>=2,'Choose priorities')}
function renderPriorities(){const cat=(state.mode==='know'?interestCatalog:discoveryCatalog).filter(x=>state.selected.has(x.id));priorityGrid.innerHTML='';cat.forEach(it=>{const b=document.createElement('button');b.className='pick text-left border-2 border-stone-200 rounded-xl p-4 bg-white'+(state.anchors.has(it.id)?' selected':'');b.innerHTML=`<div class="font-bold">${it.icon} ${it.label}</div><div class="text-sm text-stone-500 mt-1">${it.desc}</div>`;b.onclick=()=>{if(state.anchors.has(it.id))state.anchors.delete(it.id);else if(state.anchors.size<2)state.anchors.add(it.id);renderPriorities()};priorityGrid.appendChild(b)});priorityCount.textContent=`${state.anchors.size} of 2 selected`;enable(priorityNext,state.anchors.size===2,'Next')}
function renderAvoids(){avoidGrid.innerHTML='';avoidCatalog.forEach(it=>{const b=document.createElement('button');b.className='pick text-left border-2 border-stone-200 rounded-xl p-4 bg-white'+(state.avoids.has(it.id)?' avoid-selected':'');b.innerHTML=`<div class="font-bold">${it.icon} ${it.label}</div><div class="text-sm text-stone-500 mt-1">${it.desc}</div>`;b.onclick=()=>{state.avoids.has(it.id)?state.avoids.delete(it.id):state.avoids.add(it.id);renderAvoids()};avoidGrid.appendChild(b)})}
function wildcardRegion(rr){const visible=new Set(rr.slice(0,6).map(x=>x.id));return rr.find(r=>!visible.has(r.id)&&!state.savedRegions.has(r.id)&&r.obviousness<=5&&r._score>=50)||rr.find(r=>!visible.has(r.id)&&!state.savedRegions.has(r.id)&&r.obviousness<=5)||null}
function toggleRegion(id){if(state.savedRegions.has(id)){const c=(state.savedExp.get(id)||new Set()).size;if(c&&!confirm(`Remove ${regionById[id].name} and its ${c} saved experience${c===1?'':'s'} from this trip?`))return;state.savedRegions.delete(id);if(c)state.savedExp.delete(id)}else state.savedRegions.add(id);updateHeader()}


function renderResults(){
  const rr=ranked();
  regionalResults.innerHTML=rr.slice(0,6).map((r,i)=>`<article class="region-card bg-white rounded-[1.5rem] border border-stone-100 overflow-hidden">${regionResultHeader(r,i)}<div class="p-5 pt-3"><p class="text-stone-700 leading-relaxed">${regionDescription(r)}</p><div class="mt-5 pt-4 border-t border-stone-100"><p class="text-xs uppercase tracking-[.15em] font-bold text-tomato mb-2">Why it fits your choices</p><p class="text-stone-600">${whyRegion(r)}</p></div>${state.avoids.has('driving')&&r.frictions.driving>=6?`<div class="mt-3 p-3 rounded-lg bg-mist text-sm"><strong>No-car note:</strong> ${r.noCar}</div>`:''}<div class="mt-5 flex flex-col sm:flex-row gap-2"><button data-explore="${r.id}" class="exploreBtn flex-1 px-4 py-3 rounded-xl bg-basil text-white font-bold">Explore this match</button><button data-save="${r.id}" class="saveRegion flex-1 px-4 py-3 rounded-xl border-2 ${state.savedRegions.has(r.id)?'border-basil bg-mist text-basil':'border-stone-200'} font-bold">${state.savedRegions.has(r.id)?'✓ Saved for this trip':'Save for this trip'}</button></div></div></article>`).join('');
  const w=wildcardRegion(rr);
  regionalWildcardSection.innerHTML=w?`<div class="bg-ink text-white rounded-[1.6rem] p-6"><div class="text-xs uppercase tracking-[.15em] text-gold font-bold mb-2">Wildcard · an unexpected strong regional match</div><h3 class="font-display text-3xl font-bold mb-3">${w.name}</h3><p class="text-white/80">${regionDescription(w)}</p><p class="text-white/70 mt-3">${whyRegion(w)}</p><p class="text-sm text-white/55 mt-3">Wildcards are less-obvious regional choices that still fit your priorities. Hidden Gems come later and are more obscure.</p><div class="mt-5 flex gap-2"><button data-explore="${w.id}" class="exploreBtn px-4 py-3 rounded-xl bg-white text-ink font-bold">Explore</button><button data-save="${w.id}" class="saveRegion px-4 py-3 rounded-xl border border-white/30 font-bold">${state.savedRegions.has(w.id)?'✓ Saved':'Save for this trip'}</button></div></div>`:'';
  document.querySelectorAll('.saveRegion').forEach(b=>b.onclick=()=>{toggleRegion(b.dataset.save);renderResults()});
  document.querySelectorAll('.exploreBtn').forEach(b=>b.onclick=()=>openExplore(b.dataset.explore));
  viewTripIdeasTopButton.classList.toggle('hidden',!state.savedRegions.size);
  renderSavedBottom()
}
function renderSavedBottom(){if(!state.savedRegions.size){savedTripSummaryBottom.classList.add('hidden');return}savedTripSummaryBottom.classList.remove('hidden');const names=[...state.savedRegions].map(id=>regionById[id].short);savedTripSummaryBottom.innerHTML=`<div class="bg-white rounded-[1.5rem] border border-stone-100 p-6 flex flex-col md:flex-row md:justify-between gap-4"><div><p class="text-xs uppercase tracking-[.16em] font-bold text-tomato mb-2">Saved for this trip</p><h3 class="font-display text-2xl font-bold">${state.savedRegions.size} region${state.savedRegions.size===1?'':'s'} · ${totalSaved()} saved experience${totalSaved()===1?'':'s'}</h3><p class="text-stone-500 mt-2">${naturalList(names)}</p></div><button id="viewBottom" class="px-5 py-3 rounded-xl bg-basil text-white font-bold">View My Trip Ideas</button></div>`;viewBottom.onclick=()=>openTrip('region')}
function compareQuestions(a,b){const user=Object.entries(weights()).sort((x,y)=>y[1]-x[1]).map(x=>x[0]).slice(0,8);const choices=user.map(t=>({t,d:Math.abs((a.traits[t]||0)-(b.traits[t]||0))})).sort((x,y)=>y.d-x.d).filter(x=>x.d>=2).slice(0,3);const fill=['smalltown','maker','ancient','scenery','food','local','outdoor','churches','art','beach'];for(const t of fill){if(choices.length>=3)break;if(!choices.some(x=>x.t===t)&&Math.abs((a.traits[t]||0)-(b.traits[t]||0))>=2)choices.push({t})}return choices.slice(0,3)}


function renderCompare(){
  const [a,b]=ranked().slice(0,2);state.compare={a:0,b:0,i:0};compareTitle.textContent=`${a.short} or ${b.short}?`;
  compareRegionCards.innerHTML=[a,b].map(r=>`<div class="bg-white rounded-[1.5rem] border border-stone-100 overflow-hidden"><div class="p-6"><div class="text-xs uppercase tracking-[.15em] font-bold text-tomato mb-2">${fit(r._score)}</div><h3 class="font-display text-3xl font-bold mb-3">${regionTitle(r)}</h3><p class="text-sm font-bold text-stone-500 mb-2">Why it is high on your list</p><p class="text-stone-600">${whyRegion(r)}</p></div></div>`).join('');
  renderTie(a,b)
}
